#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

sudo dnf copr enable frostyx/gleam -y

sudo dnf install -y "bison" "clang-format" "clang-tidy" "cmake" "dnf-automatic" "dnf5-plugins" "entr" "gcc" "gcc-c++" "gdb" "git" "gleam" "htop" "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm" "https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm" "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm" "https://zoom.us/client/latest/zoom_x86_64.rpm" "jq" "kernel" "kernel-core" "kernel-devel" "kernel-headers" "kernel-modules" "kernel-modules-core" "kernel-modules-extra" "kernel-tools" "kernel-tools-libs" "libffi-devel" "libyaml-devel" "make" "openssl-devel" "p7zip" "python3-wheel" "shellcheck" "snapd" "solaar" "stow" "tree" "xxd" "zlib-devel" "zsh"

sudo ln -sf /var/lib/snapd/snap /snap

chsh -s "$(which zsh)"

tee -a "$HOME/.zshrc" <<'EOF'
gh_latest_tag() {
  curl -fsSL "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed 's/v//g'
}
EOF

sudo tee "/etc/dnf/automatic.conf" <<'EOF'
[commands]
apply_updates=True
EOF

mkdir -p "$HOME/.config/autostart"

tee "$HOME/.config/autostart/1password.desktop" <<'EOF'
[Desktop Entry]
Name=1Password
Exec=1password --silent %U
Terminal=false
Type=Application
Icon=1password
StartupWMClass=1Password
Comment=Password manager and secure wallet
MimeType=x-scheme-handler/onepassword;
Categories=Office;
EOF

sed -i 's/enableMiniWindow=.*/enableMiniWindow=false/' "$HOME/.config/zoomus.conf"

git config --global init.defaultBranch main
git config --global user.email "aguseranieri@gmail.com"
git config --global user.name "Agustin Ranieri"
git config --global credential.username "RaniAgus"
git config --global gpg.format ssh

sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo rpm --import -

sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1

sudo dnf install -y "1password-cli" "VirtualBox-7.2" "containerd.io" "docker" "docker-buildx-plugin" "docker-ce" "docker-ce-cli" "docker-compose-plugin" "ffmpeg" "python3-pip" "ranger" "steam" "valgrind"

tee -a "$HOME/.zshrc" <<'EOF'
# pip
export PATH="$HOME/.local/bin:$PATH"
EOF

tee -a "$HOME/.zshrc" <<'EOF'
# ffmpeg
ffprobe-duration() {
  files="${1:=$(ls)}"
  durations=$(\
    echo "$files" \
    | xargs -I{} ffprobe -show_format "{}" 2> /dev/null \
    | grep duration \
    | cut -d'=' -f2 \
    | xargs -I{} date -d@{} -u +%H:%M:%S \
  )
  paste <(echo "$durations") <(echo "$files")
}
EOF

tee -a "$HOME/.zshrc" <<'EOF'
# ranger
rcd () {
  ranger --choosedir="$HOME/.rangerdir"
  cd "$(cat "$HOME/.rangerdir")" || exit
}
bindkey -s '^o' 'rcd\n'
EOF

sudo systemctl enable --now docker
sudo groupadd docker
sudo usermod -aG docker "$USER"

tee -a "$HOME/.zshrc" <<'EOF'
alias vm="valgrind --leak-check=full --track-origins=yes"
alias vh="valgrind --tool=helgrind"
alias vn="valgrind --tool=none"
EOF

bash -c "$(curl -fsSL "https://sh.rustup.rs")"

zsh <<'EOF'
cargo install zoxide --locked
EOF

tee -a "$HOME/.zshrc" <<'EOF'
# zoxide
eval "$(zoxide init zsh)"
EOF

flatpak install -y flathub "com.discordapp.Discord" "com.github.jeromerobert.pdfarranger" "com.github.maoschanz.drawing" "com.obsproject.Studio" "net.pcsx2.PCSX2" "org.kde.kdenlive"

pip install -U "kazam" "yt-dlp[default]"

mkdir -p "$HOME/.local/share/applications"

tee "$HOME/.local/share/applications/kazam.desktop" <<'EOF'
[Desktop Entry]
Name=Kazam
Comment=Screen recording tool
Exec=kazam
Icon=kazam
Terminal=false
Type=Application
Categories=AudioVideo;Recorder;
StartupNotify=true
EOF

tee -a "$HOME/.zshrc" <<'EOF'
# yt-dlp
alias ytdl-playlist='yt-dlp -o "%(playlist_index)s-%(title)s.%(ext)s"'
alias ytdl-video='yt-dlp -o "%(title)s.%(ext)s"'
alias ytdl-audio='yt-dlp -x -o "%(title)s.%(ext)s"'
EOF

sudo snap install "code" --classic

sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo

sudo dnf install -y "gh" --repo gh-cli

curl -fsSL "https://go.dev/dl/$(curl -fsSL 'https://golang.org/VERSION?m=text' | head -n1).linux-amd64.tar.gz" | sudo tar xzvC "/usr/local"

tee -a "$HOME/.zshrc" <<'EOF'
# go
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
EOF

curl -fsSL "$(curl -fsSL "https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release" | jq -r '.TBA[0].downloads.linux.link')" | sudo tar xzvC "/opt"

# shellcheck disable=SC2211
/opt/jetbrains-toolbox-*/bin/jetbrains-toolbox

zsh -c "$(curl -fsSL "https://get.sdkman.io")"

sdk install maven
sdk install gradle
sdk install kotlin

zsh -c "$(curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/v$(gh_latest_tag nvm-sh/nvm)/install.sh")"

tee -a "$HOME/.zshrc" <<'EOF'
# nvm
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc
EOF

zsh <<'EOF'
nvm install --lts
nvm use --lts
npm i --location=global npm@latest @angular/cli corepack degit typescript yarn
EOF

zsh -c "$(curl -fsSL "https://get.pnpm.io/install.sh")"

zsh -c "$(curl -fsSL "https://bun.sh/install")"

zsh -c "$(curl -fsSL "https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer")"

zsh <<'EOF'
rbenv install -l 2> /dev/null | grep '^3' | tail -1 | xargs rbenv install
rbenv versions | xargs rbenv global
EOF

gem install pry bundler rspec colorize rails jekyll

curl -fsSL "https://downloads.sourceforge.net/project/pseint/20230517/pseint-l64-20230517.tgz" | sudo tar xzvC "/opt"

sudo snap install "postman" "spotify" "vlc"

TMP_DIR=$(mktemp -d)
git clone https://github.com/mumuki/cspec.git "$TMP_DIR"
(
  cd "$TMP_DIR"
  make
  sudo make install
)
rm -rf "$TMP_DIR"

TMP_DIR=$(mktemp -d)
git clone https://github.com/sisoputnfrba/so-commons-library.git "$TMP_DIR"
(
  cd "$TMP_DIR"
  make
  sudo make install
)
rm -rf "$TMP_DIR"

sudo mkdir -p /usr/local/include/doctest

curl -fsSL "https://raw.githubusercontent.com/doctest/doctest/v2.4.12/doctest/doctest.h" | sudo tee "/usr/local/include/doctest/doctest.h"

mkdir -p "$HOME/.local/bin"

curl -fsSL "https://github.com/stenzek/duckstation/releases/download/latest/DuckStation-x64.AppImage" | tee "$HOME/.local/bin/DuckStation-x64.AppImage"

chmod +x "$HOME/.local/bin/DuckStation-x64.AppImage"
mkdir -p "$HOME/.local/share/applications"

tee "$HOME/.local/share/applications/DuckStation-x64.desktop" <<'EOF'
[Desktop Entry]
Name=DuckStation
StartupNotify=true
Type=Application
Terminal=false
Categories=Utilities;
Exec=DuckStation-x64.AppImage
EOF

bash -c "$(curl -fsSL "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh")"

TMP_FILE=$(mktemp)
curl -fsSL "https://github.com/ryanoasis/nerd-fonts/releases/download/v$(gh_latest_tag ryanoasis/nerd-fonts)/JetBrainsMono.zip" -o "$TMP_FILE"
sudo unzip "$TMP_FILE" -d "/usr/share/fonts/JetBrainsMonoNerdFont"
rm "$TMP_FILE"

rm -rf "$HOME/.oh-my-zsh"

bash -c "$(curl -fsSL "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh")"

zsh <<'EOF'
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
EOF

sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' "$HOME/.zshrc"

mkdir -p "$HOME/.oh-my-posh/bin"

bash -c "$(curl -fsSL "https://ohmyposh.dev/install.sh")"

tee "$HOME/.config/oh-my-posh/zen.toml" <<'EOF'
#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightBlue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = "dotnet"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "#6a0dad"
    template = " 󰪮 {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#00add8"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "ruby"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#7a1045"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "node"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#3c873a"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "angular"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "#a6120d"
    template = "{{ if .Full }}  {{ .Full }} {{ end }}"

  [[blocks.segments]]
    type = "react"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "blue"
    template = "{{ if .Full }}  {{ .Full }} {{ end }}"

  [[blocks.segments]]
    type = "java"
    style = "powerline"
    powerline_symbol = ""
    foreground = "blue"
    background = "#ec833f"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = 'terraform'
    style = 'powerline'
    powerline_symbol = ""
    foreground = "white"
    background = "magenta"
    template = " 󱁢 {{ .WorkspaceName }} "

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'green'
  background = 'transparent'
  template = '❯❯ '
EOF