#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

sudo dnf install -y snapd

sudo ln -s /var/lib/snapd/snap /snap

sudo dnf install -y zsh

sh -c "$(wget "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh" -O -)"
chsh -s $(which zsh)

tee -a ~/.zshrc <<'EOF'
gh_latest_tag() {
  curl -fsSL "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed 's/v//g'
}
EOF

sudo dnf install -y python3-pip

tee -a ~/.zshrc <<'EOF'
# pip
export PATH="$HOME/.local/bin:$PATH"
EOF

sudo dnf install -y dnf-automatic

sudo tee /etc/dnf/automatic.conf <<'EOF'
[commands]
apply_updates=True
EOF

sudo dnf install -y make cmake gcc gcc-c++

sudo dnf install -y p7zip

sudo dnf install -y entr

sudo dnf install -y ffmpeg

tee -a ~/.zshrc <<'EOF'
# ffmpeg
ffprobe-duration() {
  files="${1:=$(ls)}"
  durations=$(\
    echo "$files" \
    | xargs -I{} ffprobe -show_format "{}" 2> /dev/null \
    | grep duration \
    | cut -d'=' -f2 \
    | xargs -I{} date -d@{} -u +%H:%M:%S \
  )
  paste <(echo "$durations") <(echo "$files")
}
EOF

sudo dnf install -y htop

sudo dnf install -y jq

sudo dnf install -y ranger

tee -a ~/.zshrc <<'EOF'
# ranger
rcd () {
  ranger --choosedir="$HOME/.rangerdir"
  cd "$(cat "$HOME/.rangerdir")" || exit
}
bindkey -s '^o' 'rcd\n'
EOF

sudo dnf install -y stow

sudo dnf install -y tree

sudo dnf install -y xxd

bash -c "$(curl -fsSL "https://sh.rustup.rs")"

zsh <<'EOF'
cargo install zoxide --locked
EOF

tee -a ~/.zshrc <<'EOF'
# zoxide
eval "$(zoxide init zsh)"
EOF

sudo dnf install -y solaar

sudo dnf install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

sudo dnf install -y https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm

tee ~/.config/autostart/1password.desktop <<'EOF'
[Desktop Entry]
Name=1Password
Exec=1password --silent %U
Terminal=false
Type=Application
Icon=1password
StartupWMClass=1Password
Comment=Password manager and secure wallet
MimeType=x-scheme-handler/onepassword;
Categories=Office;
EOF

sudo dnf install -y 1password-cli

sudo dnf install -y https://zoom.us/client/latest/zoom_x86_64.rpm

sed -i 's/enableMiniWindow=.*/enableMiniWindow=false/' ~/.config/zoomus.conf

flatpak install -y flathub org.kde.kdenlive

flatpak install -y flathub com.github.jeromerobert.pdfarranger

flatpak install -y flathub com.obsproject.Studio

flatpak install -y flathub com.github.maoschanz.drawing

sudo dnf install -y python3-wheel zlib-devel

pip install -U kazam

tee ~/.local/share/applications/kazam.desktop <<'EOF'
[Desktop Entry]
Name=Kazam
Comment=Screen recording tool
Exec=kazam
Icon=kazam
Terminal=false
Type=Application
Categories=AudioVideo;Recorder;
StartupNotify=true
EOF

pip install -U yt-dlp[default]

tee -a ~/.zshrc <<'EOF'
# yt-dlp
alias ytdl-playlist='yt-dlp -o "%(playlist_index)s-%(title)s.%(ext)s"'
alias ytdl-video='yt-dlp -o "%(title)s.%(ext)s"'
alias ytdl-audio='yt-dlp -x -o "%(title)s.%(ext)s"'
EOF

sudo dnf install -y dnf5-plugins

sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

sudo dnf install -y docker docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

sudo systemctl enable --now docker
sudo groupadd docker
sudo usemod -aG docker $USER

sudo dnf install -y kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra kernel-tools kernel-tools-libs kernel-headers kernel-devel

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo rpm --import -

sudo dnf install -y VirtualBox-7.2

sudo snap install code --classic

sudo dnf install -y git

git config --global init.defaultBranch main
git config --global user.email "aguseranieri@gmail.com"
git config --global user.name "Agustin Ranieri"
git config --global credential.username "RaniAgus"
git config --global gpg.format ssh

sudo dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo

sudo dnf install -y gh --repo gh-cli

curl -fsSL "https://go.dev/dl/$(curl -fsSL 'https://golang.org/VERSION?m=text' | head -n1).linux-amd64.tar.gz" | sudo tar xzvC /usr/local

tee -a ~/.zshrc <<'EOF'
# go
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
EOF

curl -fsSL "$(curl -fsSL "https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release" | jq -r '.TBA[0].downloads.linux.link')" | sudo tar xzvC /opt

/opt/jetbrains-toolbox-*/bin/jetbrains-toolbox

zsh -c "$(curl -fsSL "https://get.sdkman.io")"

sdk install maven
sdk install gradle
sdk install kotlin

zsh -c "$(curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/v$(gh_latest_tag nvm-sh/nvm)/install.sh")"

tee -a ~/.zshrc <<'EOF'
# nvm
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc
EOF

zsh <<'EOF'
nvm install --lts
nvm use --lts
npm i --location=global npm@latest @angular/cli corepack degit typescript yarn
EOF

zsh -c "$(curl -fsSL "https://get.pnpm.io/install.sh")"

zsh -c "$(curl -fsSL "https://bun.sh/install")"

sudo dnf install -y openssl-devel zlib-devel libyaml-devel libffi-devel bison

zsh -c "$(curl -fsSL "https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer")"

zsh <<'EOF'
rbenv install -l 2> /dev/null | grep '^3' | tail -1 | xargs rbenv install
rbenv versions | xargs rbenv global
EOF

gem install pry bundler rspec colorize rails jekyll

curl -fsSL "https://downloads.sourceforge.net/project/pseint/20230517/pseint-l64-20230517.tgz" | sudo tar xzvC /opt

sudo snap install postman

sudo dnf install -y gdb

sudo dnf install -y clang-tidy

sudo dnf install -y clang-format

TMP_DIR=$(mktemp -d)
git clone https://github.com/mumuki/cspec.git $TMP_DIR
(
  cd $TMP_DIR
  make
  sudo make install
)
rm -rf $TMP_DIR

TMP_DIR=$(mktemp -d)
git clone https://github.com/sisoputnfrba/so-commons-library.git $TMP_DIR
(
  cd $TMP_DIR
  make
  sudo make install
)
rm -rf $TMP_DIR

curl -fsSL "https://raw.githubusercontent.com/doctest/doctest/v2.4.12/doctest/doctest.h" | sudo tee /usr/local/include/doctest

sudo dnf install -y valgrind

tee -a ~/.zshrc <<'EOF'
alias vm="valgrind --leak-check=full --track-origins=yes"
alias vh="valgrind --tool=helgrind"
alias vn="valgrind --tool=none"
EOF

sudo snap install vlc

sudo snap install spotify

flatpak install -y flathub com.discordapp.Discord

curl -fsSL "https://github.com/stenzek/duckstation/releases/download/latest/DuckStation-x64.AppImage" | tee ~/.local/bin/DuckStation-x64.AppImage

tee ~/.local/share/applications/DuckStation-x64.desktop <<'EOF'
[Desktop Entry]
Name=DuckStation
StartupNotify=true
Type=Application
Terminal=false
Categories=Utilities;
Exec=DuckStation-x64.AppImage
EOF

flatpak install -y flathub net.pcsx2.PCSX2

sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1

sudo dnf install -y steam

bash -c "$(curl -fsSL "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh")"

TMP_FILE=$(mktemp)
curl -fsSL "https://github.com/ryanoasis/nerd-fonts/releases/download/v$(gh_latest_tag ryanoasis/nerd-fonts)/JetBrainsMono.zip" -o $TMP_FILE
sudo unzip $TMP_FILE -d /usr/share/fonts/JetBrainsMonoNerdFont
rm $TMP_FILE

bash -c "$(curl -fsSL "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh")"

zsh <<'EOF'
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting"
EOF

sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc

mkdir -p $HOME/.oh-my-posh/bin

bash -c "$(curl -fsSL "https://ohmyposh.dev/install.sh")"

tee $HOME/.config/oh-my-posh/zen.toml <<'EOF'
#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'lightBlue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = "dotnet"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "#6a0dad"
    template = " 󰪮 {{ .Full }} "

  [[blocks.segments]]
    type = "go"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#00add8"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "ruby"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#7a1045"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "node"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#3c873a"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = "angular"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "#a6120d"
    template = "{{ if .Full }}  {{ .Full }} {{ end }}"

  [[blocks.segments]]
    type = "react"
    style = "powerline"
    powerline_symbol = ""
    foreground = "white"
    background = "blue"
    template = "{{ if .Full }}  {{ .Full }} {{ end }}"

  [[blocks.segments]]
    type = "java"
    style = "powerline"
    powerline_symbol = ""
    foreground = "blue"
    background = "#ec833f"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = 'terraform'
    style = 'powerline'
    powerline_symbol = ""
    foreground = "white"
    background = "magenta"
    template = " 󱁢 {{ .WorkspaceName }} "

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'green'
  background = 'transparent'
  template = '❯❯ '
EOF